'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs'); const os = require('os'); const path = require('path');
const Tx = require('../../src/core/agent-runtime/change-transaction');
function temp() { return fs.mkdtempSync(path.join(os.tmpdir(), 'tangbao-tx-')); }

test('原子创建、写入、移动、删除产生哈希证据', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'a.txt'),'old'); const tx=Tx.plan(root,[{type:'write',path:'a.txt',content:'new'},{type:'create',path:'b.txt',content:'b'}]); const r=Tx.commit(tx); assert.equal(r.ok,true); assert.equal(fs.readFileSync(path.join(root,'a.txt'),'utf8'),'new'); assert.equal(r.changes.length,2); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('预期哈希冲突阻止写入', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'a'),'x'); assert.throws(()=>Tx.plan(root,[{type:'write',path:'a',content:'y',expectedHash:'bad'}]),/哈希冲突/); assert.equal(fs.readFileSync(path.join(root,'a'),'utf8'),'x'); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('多文件中途失败自动恢复已提交项', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'a'),'A'); fs.writeFileSync(path.join(root,'b'),'B'); const tx=Tx.plan(root,[{type:'write',path:'a',content:'AA'},{type:'write',path:'b',content:'BB'}]); const r=Tx.commit(tx,{failAt:1}); assert.equal(r.ok,false); assert.equal(fs.readFileSync(path.join(root,'a'),'utf8'),'A'); assert.equal(fs.readFileSync(path.join(root,'b'),'utf8'),'B'); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('提交前外部修改阻止事务', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'a'),'A'); const tx=Tx.plan(root,[{type:'write',path:'a',content:'B'}]); fs.writeFileSync(path.join(root,'a'),'external'); const r=Tx.commit(tx); assert.equal(r.ok,false); assert.equal(r.error.code,'hash_mismatch'); assert.equal(fs.readFileSync(path.join(root,'a'),'utf8'),'external'); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('运行级回滚覆盖创建删除移动和写入', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'write.txt'),'old'); fs.writeFileSync(path.join(root,'delete.txt'),'gone'); fs.writeFileSync(path.join(root,'move.txt'),'move'); const tx=Tx.plan(root,[{type:'write',path:'write.txt',content:'new'},{type:'create',path:'created.txt',content:'created'},{type:'delete',path:'delete.txt'},{type:'move',path:'move.txt',to:'moved.txt'}]); const committed=Tx.commit(tx); assert.equal(committed.ok,true); const changes=tx.operations.map((item)=>({operation:item.type,path:item.path,to:item.to,afterHash:item.afterHash,beforeExists:item.before.exists,beforeContent:item.before.content&&item.before.content.toString('base64')})); const rolled=Tx.rollback(root,changes); assert.equal(rolled.ok,true); assert.equal(fs.readFileSync(path.join(root,'write.txt'),'utf8'),'old'); assert.equal(fs.existsSync(path.join(root,'created.txt')),false); assert.equal(fs.readFileSync(path.join(root,'delete.txt'),'utf8'),'gone'); assert.equal(fs.readFileSync(path.join(root,'move.txt'),'utf8'),'move'); assert.equal(fs.existsSync(path.join(root,'moved.txt')),false); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('回滚前外部修改会整批阻止且不做部分恢复', () => { const root=temp(); try { fs.writeFileSync(path.join(root,'a'),'A'); fs.writeFileSync(path.join(root,'b'),'B'); const tx=Tx.plan(root,[{type:'write',path:'a',content:'AA'},{type:'write',path:'b',content:'BB'}]); assert.equal(Tx.commit(tx).ok,true); fs.writeFileSync(path.join(root,'b'),'external'); const changes=tx.operations.map((item)=>({operation:item.type,path:item.path,afterHash:item.afterHash,beforeExists:true,beforeContent:item.before.content.toString('base64')})); const rolled=Tx.rollback(root,changes); assert.equal(rolled.ok,false); assert.deepEqual(rolled.conflicts,['b']); assert.equal(fs.readFileSync(path.join(root,'a'),'utf8'),'AA'); } finally { fs.rmSync(root,{recursive:true,force:true}); } });
test('分页游标不重复结果', () => { const a=Tx.page([1,2,3,4],0,2); const b=Tx.page([1,2,3,4],a.nextCursor,2); assert.deepEqual(a.items,[1,2]); assert.deepEqual(b.items,[3,4]); assert.equal(b.nextCursor,null); });
