'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fsp=require('fs/promises'),path=require('path'),os=require('os');const Security=require('../../src/core/skills/skill-security');
async function fixture(script){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'tb-sec-')),dir=path.join(root,'secure');await fsp.mkdir(path.join(dir,'scripts'),{recursive:true});await fsp.writeFile(path.join(dir,'SKILL.md'),'---\nname: secure\ndescription: Secure\nallowed-tools: read_file run_skill_script write_file\nmetadata:\n  platforms: [win32]\n  runtimes:\n    python: ">=3.10"\n---\nBody');await fsp.writeFile(path.join(dir,'scripts','run.js'),script);return{root,dir};}
test('扫描网络/环境变量风险并生成能力标签',async()=>{const x=await fixture('fetch("https://x"); console.log(process.env.API_KEY)');try{const r=await Security.scan(x.dir);assert.ok(r.risks.some(x=>x.type==='network'));assert.ok(r.risks.some(x=>x.type==='environment'));assert.ok(r.capabilities.includes('进程执行'));assert.ok(r.capabilities.includes('网络访问'));}finally{await fsp.rm(x.root,{recursive:true,force:true});}});
test('allowed-tools 只能取系统权限交集',()=>assert.deepEqual(Security.effectiveAllowedTools('read_file run_skill_script write_file',['read_file','run_skill_script']),['read_file','run_skill_script']));
test('信任仅绑定当前包哈希',async()=>{const x=await fixture('console.log(1)');try{const scan=await Security.scan(x.dir);await Security.writeTrust(x.dir,{packageHash:scan.packageHash,level:'version'});assert.equal((await Security.trustStatus(x.dir,scan.packageHash)).trusted,true);assert.equal((await Security.trustStatus(x.dir,'changed')).reason,'hash_changed');}finally{await fsp.rm(x.root,{recursive:true,force:true});}});
test('兼容性报告平台和运行时缺口',async()=>{const x=await fixture('');try{const meta=require('../../src/core/skills/skill-registry').readSkillMeta(x.dir);const r=Security.compatibility(await meta,{platform:'linux',executables:{}});assert.equal(r.ok,false);assert.ok(r.issues.some(x=>x.code==='platform'));assert.ok(r.issues.some(x=>x.code==='runtime'));}finally{await fsp.rm(x.root,{recursive:true,force:true});}});
test('触发词冲突可诊断',()=>assert.equal(Security.triggerConflicts([{name:'a',triggers:['检查']},{name:'b',triggers:['检查']}]).length,1));
test('未安装包可在落盘前扫描风险',async()=>{const x=await fixture('fetch("https://x")');try{const Registry=require('../../src/core/skills/skill-registry');const pkg=await Registry.packageFromDirectory(x.dir);const r=Security.scanPackage(pkg);assert.equal(r.score,'high');assert.ok(r.risks.some(item=>item.type==='network'));}finally{await fsp.rm(x.root,{recursive:true,force:true});}});
test('最低糖包版本参与兼容性判断',()=>{const r=Security.compatibility({metadata:{minTangbaoVersion:'2.0.0'}},{platform:process.platform,tangbaoVersion:'1.0.6',executables:{}});assert.equal(r.ok,false);assert.ok(r.issues.some(item=>item.code==='tangbao-version'));});
