'use strict';
const READ_ONLY_TOOLS={explore:['get_repo_map','read_file','read_files','get_file_outline','list_dir','glob','grep','find_symbol','find_references'],test:['get_repo_map','read_file','read_files','list_dir','glob','grep','detect_verification','run_tests','run_lint','run_typecheck'],review:['get_repo_map','read_file','read_files','list_dir','glob','grep','git_status','git_diff','git_log','git_changed_files','find_symbol','find_references']};
function create(options){const opts=Object.assign({maxDepth:2,maxConcurrent:3,maxChildren:8},options||{});const records=new Map();let active=0,counter=0;function descriptor(input,parent){const role=String(input.role||input.type||'');if(!READ_ONLY_TOOLS[role])throw Object.assign(new Error('未知子任务角色：'+role),{code:'invalid_role'});const depth=Number(parent&&parent.depth||0)+1;if(depth>opts.maxDepth)throw Object.assign(new Error('超过子任务最大深度'),{code:'max_depth'});const parentRunId=String(input.parentRunId||parent&&parent.id||'');if(Array.from(records.values()).filter((item)=>item.parentRunId===parentRunId).length>=opts.maxChildren)throw Object.assign(new Error('超过该父任务的子任务数量上限'),{code:'max_children'});return{id:String(input.id||('child_'+Date.now().toString(36)+'_'+(++counter))),parentRunId,role,depth,goal:String(input.goal||'').slice(0,1000),allowedTools:READ_ONLY_TOOLS[role].slice(),readOnly:true,budget:Object.assign({maxSteps:8,maxTokens:0},input.budget||{}),status:'pending',createdAt:Date.now(),startedAt:0,finishedAt:0,result:null,error:''};}
function add(input,parent){const item=descriptor(input,parent);records.set(item.id,item);return item;}
function start(id){const item=records.get(id);if(!item)throw Object.assign(new Error('子任务不存在'),{code:'not_found'});if(active>=opts.maxConcurrent)throw Object.assign(new Error('达到子任务并发上限'),{code:'max_concurrent'});if(item.status!=='pending')throw Object.assign(new Error('子任务状态不可启动'),{code:'invalid_status'});item.status='running';item.startedAt=Date.now();active++;return item;}
function finish(id,result){const item=records.get(id);if(!item)return null;if(item.status==='running')active=Math.max(0,active-1);item.status=result&&result.ok===false?'failed':'completed';item.finishedAt=Date.now();item.result=result||null;item.error=result&&result.ok===false?String(result.summary||result.error||'failed'):'';return item;}
function cancel(id,reason){const item=records.get(id);if(!item)return null;if(item.status==='running')active=Math.max(0,active-1);if(item.status==='completed'||item.status==='failed')return item;item.status='cancelled';item.error=String(reason||'parent_cancelled');item.finishedAt=Date.now();return item;}
function cancelByParent(parentRunId,reason){const out=[];for(const item of records.values())if(item.parentRunId===parentRunId&&(item.status==='pending'||item.status==='running'))out.push(cancel(item.id,reason));return out;}
function gate(parentRunId){const items=Array.from(records.values()).filter((x)=>x.parentRunId===parentRunId);return{pending:items.filter((x)=>x.status==='pending'||x.status==='running'),failed:items.filter((x)=>x.status==='failed'),cancelled:items.filter((x)=>x.status==='cancelled'),completed:items.filter((x)=>x.status==='completed')};}
function snapshot(){return{schemaVersion:1,options:opts,records:Array.from(records.values()),active};}
function restore(snapshot){records.clear();active=0;for(const raw of snapshot&&snapshot.records||[]){const item=Object.assign({},raw);if(item.status==='running')item.status='pending';records.set(item.id,item);}return snapshot?records.size:0;}
return{add,start,finish,cancel,cancelByParent,gate,snapshot,restore,get:(id)=>records.get(id),list:()=>Array.from(records.values())};}
module.exports={READ_ONLY_TOOLS,create};
